### ISSUE TITLE
Issues  on Xiaomi mi air 13 - 2018 - I5

### ISSUE THREAD

**Issue by nelbrodrigues** [yllwfsh/Xiaomi-Notebook-Air-13.3-2018-macOS-EFI#2]
Hi, these files have worked great for me but I'm struggling to fix some problems.

1- Random shutdowns and restarts: Sometimes it happens when i start the OS. I found it's somewhat related to the Windows volume being mounted at the Osx start. If i quickly unmount these volumes the OS runs smoothly. It happens too if I use touchpad only.
I'm trying to prevent these volumes from mounting on boot but I'm strugglin.

2- Somehow battery drain: I don't know much about it but it looks like battery drains too quickly. I discovered i cant plug the wifi usb to a dongle because it turns hot very fast and drains the battery.

3- Audio: My audio is great on speakers but awful on headphones. It's like i can feel only instruments in a song. Quite weird.

Other than this the OS is very fast and I can mount videos and edit pictures and having it stable most of the time using an external mouse and unmounting windows volumes.

**Comment by yllwfsh** [comment]
Hi @nelbrodrigues ,

1. Unfortunately I cannot reproduce this, since I avoid using windows at all cost ;) I have a separate SSD with Linux on it and no stability issues. Did you also try First Aid in Disk Utility? Maybe there's a problem with the macOS partition itself. Worst case you could try re-installing windows or macOS.

2. Yes it's true that the battery life is a little shorter than on Linux (or possibly Windows). I usually get about 5-6 hours of average use though. Is your laptop getting unusually warm/hot? Maybe there's a program or system process draining the battery. The battery indicator also has some good info on which program is draining the battery the most:
![image](https://user-images.githubusercontent.com/43885719/59567256-ab383a00-906b-11e9-90b1-f15b2024e59e.png)

3. You might want to do the ALCPlugFix, I've added it to the project, instructions are on the README page.

Good luck with the fixes!

**Comment by nelbrodrigues** [comment]
1. Found the way by preventing volumes of windows from mounting at start using "sudo vifs" and having:
UUID= "volumeuuid"  ntfs rw, noauto. Or something like that. Worked.

2. For the battery drain I still have to search for it. I think its a dongle problem. If I connect wifi through dongle it gets way too hot.

3. I Installed it a couple of days ago because I saw the other comment here pointing it out. It works great. 

For now Its really stable.

**Comment by yllwfsh** [comment]
Great to hear it's been running more stable now! Great idea to stop automoubting the Windows volume! Welcome to the hackintosh community ;)

If there's any other issue please feel welcome to open another issue, it's always good to improve things for everyone.
